name: Mule Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build & Deploy to CloudHub
        run: mvn clean deploy -DmuleDeploy
        env:
          anypoint.username: ${{ secrets.ANYPOINT_USERNAME }}
          anypoint.password: ${{ secrets.ANYPOINT_PASSWORD }}
